# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
