# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0002_postfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfile',
            name='name',
        ),
    ]
