# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0003_remove_postfile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
