# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0009_auto_20161218_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirWater_EquipmentConsumable',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('docfile1', models.FileField(default='', upload_to='AirWater_EquipmentConsumables/')),
                ('docfile2', models.FileField(default='', upload_to='AirWater_EquipmentConsumables/')),
                ('docfile3', models.FileField(default='', upload_to='AirWater_EquipmentConsumables/')),
                ('docfile4', models.FileField(default='', upload_to='AirWater_EquipmentConsumables/')),
                ('docfile5', models.FileField(default='', upload_to='AirWater_EquipmentConsumables/')),
            ],
        ),
        migrations.CreateModel(
            name='AirWater_Filter',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('docfile1', models.FileField(default='', upload_to='AirWater_Filters/')),
                ('docfile2', models.FileField(default='', upload_to='AirWater_Filters/')),
                ('docfile3', models.FileField(default='', upload_to='AirWater_Filters/')),
                ('docfile4', models.FileField(default='', upload_to='AirWater_Filters/')),
                ('docfile5', models.FileField(default='', upload_to='AirWater_Filters/')),
            ],
        ),
        migrations.DeleteModel(
            name='Category1_Product',
        ),
        migrations.DeleteModel(
            name='Category2_Product',
        ),
        migrations.DeleteModel(
            name='Category3_Product',
        ),
        migrations.DeleteModel(
            name='Category4_Product',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='docfile',
            new_name='docfile1',
        ),
        migrations.AddField(
            model_name='post',
            name='docfile2',
            field=models.FileField(default='', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
        migrations.AddField(
            model_name='post',
            name='docfile3',
            field=models.FileField(default='', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
        migrations.AddField(
            model_name='post',
            name='docfile4',
            field=models.FileField(default='', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
        migrations.AddField(
            model_name='post',
            name='docfile5',
            field=models.FileField(default='', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
    ]
