# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0011_auto_20161222_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airwater_equipmentconsumable',
            old_name='docfile1',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='airwater_filter',
            old_name='docfile1',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='docfile1',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='airwater_equipmentconsumable',
            name='docfile2',
        ),
        migrations.RemoveField(
            model_name='airwater_equipmentconsumable',
            name='docfile3',
        ),
        migrations.RemoveField(
            model_name='airwater_equipmentconsumable',
            name='docfile4',
        ),
        migrations.RemoveField(
            model_name='airwater_equipmentconsumable',
            name='docfile5',
        ),
        migrations.RemoveField(
            model_name='airwater_filter',
            name='docfile2',
        ),
        migrations.RemoveField(
            model_name='airwater_filter',
            name='docfile3',
        ),
        migrations.RemoveField(
            model_name='airwater_filter',
            name='docfile4',
        ),
        migrations.RemoveField(
            model_name='airwater_filter',
            name='docfile5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='docfile2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='docfile3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='docfile4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='docfile5',
        ),
        migrations.AddField(
            model_name='airwater_equipmentconsumable',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airwater_filter',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
