# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0020_auto_20170103_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='gh.mp4', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
    ]
