# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirWater_EquipmentConsumable',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='AirWater_EquipmentConsumables/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirWater_Filter',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='AirWater_Filters/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image_file', models.FileField(default='gh.png', upload_to='Posts/Year: %Y/Month: %m/Day: %d')),
                ('video_file', models.FileField(blank=True, upload_to='Posts/Year: %Y/Month: %m/Day: %d')),
                ('video_exists', models.BooleanField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
