# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:35
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0003_auto_20170104_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_exists',
            new_name='show_video',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
