# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:03
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0003_auto_20170104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
