# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:08
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0004_auto_20170104_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
