# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 07:49
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0007_auto_20170105_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
