# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0007_auto_20161218_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='docfile',
            field=models.FileField(default='', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
    ]
