# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0008_auto_20161218_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1_product',
            name='docfile',
            field=models.FileField(default='NULL.jpg', upload_to='Category1_Products/'),
        ),
        migrations.AlterField(
            model_name='category2_product',
            name='docfile',
            field=models.FileField(default='NULL.jpg', upload_to='Category2_Products/'),
        ),
        migrations.AlterField(
            model_name='category3_product',
            name='docfile',
            field=models.FileField(default='NULL.jpg', upload_to='Category3_Products/'),
        ),
        migrations.AlterField(
            model_name='category4_product',
            name='docfile',
            field=models.FileField(default='NULL.jpg', upload_to='Category4_Products/'),
        ),
    ]
