# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0011_productcatalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='file',
            field=models.FileField(upload_to=b''),
        ),
    ]
