# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0013_auto_20170626_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
