# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0019_auto_20161228_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='gh.png', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
            preserve_default=False,
        ),
    ]
