# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0022_auto_20170103_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(default='null', upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
    ]
