# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0023_auto_20170103_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='video_exists',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, upload_to='Posts/Year: %Y/Month: %m/Day: %d'),
        ),
    ]
