# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gh_app', '0024_auto_20170103_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_exists',
        ),
    ]
